# number guessing game
def Game1():
    print('Welcome to the Number Guessing Magic Trick!!!!')
    print('Lets Begin!')
    print('Think of ANY Number')
    s0=input('Please press enter once you are done')
    print('Now MULTIPLY that number with 2')
    s1=input('Done? If yes then press enter again.')
    print('Now ADD 10 to your result.')
    s2=input('Done? If yes then press enter again.')
    print('Great we are almost there......')
    print('Now DIVIDE the result by 2')
    s3=input('Done? If yes then press enter again.')
    print('yay! You reached at the final step')
    print('Now SUBTRACT your original number from your result.')
    s4=input('Done? If yes then press enter again.')
    print('So Are you ready to see the magic?')
    print('So the final result is: ..............')
    print('.')
    print('.')
    print('.')
    print('.')
    print('5')
def Game2():
    print('Welcome to the Original Number Guessing Magic Trick!!!!')
    print('Lets Begin!')
    print('Think of ANY Number')
    l0=input('Please press enter once you are done')
    print('Now MULTIPLY that number with 2')
    l1=input('Done? If yes then press enter again.')
    print('Now ADD 8 to your result.')
    l2=input('Done? If yes then press enter again.')
    print('Great we are almost there......')
    print('Now DIVIDE the result by 2')
    l3=input('Done? If yes then press enter again.')
    print('yay! You reached at the final step')
    l4=int(input('Enter the result you got after all calculations: '))
    print('Now I am gonna guess your original number.')
    print('So Are you excited for the magic to happen?')
    result=l4-4
    print('The final result is: ..............')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print('.')
    print(result)
Game1()
Game2()